version: '3'

services:
  web:
    image: tenantservice_web
    hostname: tenant.digitalfunk.io
    ports:
      - "8616:8616"
      - "8617:8617"
    networks:
      - back-tier
    volumes:
      - /code
    environment:
      - HOST_IP=${HOST_IP}
      - REDIS_HOST_IP=${REDIS_HOST_IP}
      - DISCOVERY_HOST_IP=${DISCOVERY_HOST_IP}
      - ETCD_HOST_IP=${ETCD_HOST_IP}
      - MONGO_HOST_IP=${MONGO_HOST_IP}
      - SERVICE_NAME=TenantService
      - STAGE=${STAGE}
      - CONFIG_HOST=${CONFIG_HOST}
      - CONFIG_PORT=${CONFIG_PORT}
      - INTERLOCK_DATA={"hostname":"tenant", "domain":"digitalfunk.io"}
    extra_hosts:
      - "cdsp.digitalfunk.io:${HOST_IP}"
      - "mongo.digitalfunk.io:${MONGO_HOST_IP}"
      - "etcd.digitalfunk.io:${ETCD_HOST_IP}"
      - "redis.digitalfunk.io:${REDIS_HOST_IP}"
      - "discovery.digitalfunk.io:${DISCOVERY_HOST_IP}"
networks:
    back-tier:
        external: true